data = {
    "VERSION": "2.1.4.6",
    "BASE_CDN": "https://ekyc-web.vnpt.vn",
    "BACKEND_URL": "https://api.idg.vnpt.vn/",
    "TOKEN_KEY": "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKIn9bLzBhbHYZJgTn0pbKvKdYd7l5tdftYg7qrLPqpnE8lArWlruUwcT9lH6dd6sLakzB5GMzKogoXFTrQ9gJsCAwEAAQ==",
    "TOKEN_ID": "0bb2374c-ae63-01c4-e063-62199f0a38e6",
    "AUTHORIZION": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmIyMzYwNS1mY2IyLTZlOWMtZTA2My02MjE5OWYwYTU3ZDgiLCJhdWQiOlsicmVzdHNlcnZpY2UiXSwidXNlcl9uYW1lIjoibm1odW5nMTkwMzk4QGdtYWlsLmNvbSIsInNjb3BlIjpbInJlYWQiXSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QiLCJuYW1lIjoibm1odW5nMTkwMzk4QGdtYWlsLmNvbSIsImV4cCI6MTcwMTcwOTAyNywidXVpZF9hY2NvdW50IjoiMGJiMjM2MDUtZmNiMi02ZTljLWUwNjMtNjIxOTlmMGE1N2Q4IiwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdLCJqdGkiOiIxOWRhYmU2NS0yMTNkLTQzNzgtYmYzZC1jYTllNzM5ODlhODgiLCJjbGllbnRfaWQiOiJzZGt3ZWIifQ.b3HQqDMpLz7csxbhEb7Js2htahLrjnThLXfkUlNLa92VJvqJar7mn_YehUBWtmyCNkG26EgK9ZXgzURnDRRWhPFwwQD7YXeR3pHHLMwUvKw3wS6xBxaeaYrnP6mPgxamAgiYlbeXXNOk0YEE-FSYV2u2-RDCZ9XO7Op-uXUibOmEuBCA18BkydXw4n4HAl7Nl_wNaSa4-aO7xcpSyA2tzIJ6POn5YYS39Y3X4OsFKNK1tceXqnVgJ6Tw68QyO3fj_Dq9Wcv7tf56an-6ttt5HhK6YUmpaS0tBK_nTj-4mXEThjTKpmfsJrRnzBYXlOZ43wxF8RNaW8Am3Hu9mFLrHw",
    "PARRENT_ID": "ekyc_sdk_intergrated",
    "FLOW_TYPE": "DOCUMENT",
    "SHOW_HELP": false,
    "SHOW_TRADEMARK": false,
    "CHECK_LIVENESS_CARD": true,
    "CHECK_LIVENESS_FACE": true,
    "CHECK_MASKED_FACE": true,
    "COMPARE_FACE": true,
    "LANGUAGE": "vi",
    "LIST_ITEM": [
        -1,
        5,
        6,
        7,
        9
    ],
    "TYPE_DOCUMENT": 99,
    "USE_WEBCAM": true,
    "USE_UPLOAD": true,
    "ADVANCE_LIVENESS_FACE": true,
    "ASYNC_LOAD_AI": true,
    "LIST_CHOOSE_STYLE": {
        "text_color": "black",
        "item_active_color": "#18D696",
        "background_icon": "#18D696",
        "id_icon": "https://ekyc-web.vnpt.vn/images/si/id_card.svg",
        "passport_icon": "https://ekyc-web.vnpt.vn/images/si/passport.svg",
        "drivecard_icon": "https://ekyc-web.vnpt.vn/images/si/drivecard.svg",
        "army_id_icon": "https://ekyc-web.vnpt.vn/images/si/other_doc.svg",
        "id_chip_icon": "https://ekyc-web.vnpt.vn/images/si/id_chip.svg",
        "start_button_background": "#18D696",
        "start_button_color": "#111127"
    },
    "CAPTURE_IMAGE_STYLE": {
        "big_title_color": "black",
        "description1_color": "black",
        "capture_btn_background": "#18D696",
        "capture_btn_color": "#000000",
        "capture_btn_icon": "https://ekyc-web.vnpt.vn/images/hdbank2/capture.svg",
        "tutorial_btn_icon": "https://ekyc-web.vnpt.vn/images/hdbank/help.gif",
        "upload_btn_background": "white",
        "upload_btn_color": "#000000",
        "upload_btn_boder": "2px solid #18d696",
        "upload_btn_icon": "https://ekyc-web.vnpt.vn/images/altiss/upload.svg",
        "recapture_btn_background": "#18D696",
        "recapture_btn_color": "#fff",
        "recapture_btn_border": "2px solid #18D696",
        "recapture_btn_icon": "https://ekyc-web.vnpt.vn/images/hdbank2/capture.svg",
        "nextstep_btn_background": "#18D696",
        "nextstep_btn_color": "black",
        "nextstep_btn_icon": "https://ekyc-web.vnpt.vn/images/hdbank2/next_icon.svg",
        "capture_and_upload_wrapper_bg": "rgba(23, 24, 28, 0.7);",
        "capture_and_upload_wrapper_bg_img": "https://ekyc-web.vnpt.vn/altiss/bg-img.svg"
    },
    "MODAL_DOC_STYLE": {
        "touch_icon": "https://ekyc-web.vnpt.vn/altiss/touch_cmt.svg",
        "close_icon": "https://ekyc-web.vnpt.vn/altiss/close_icon.svg",
        "notice1_icon": "https://ekyc-web.vnpt.vn/altiss/cmt_notice1.svg",
        "notice2_icon": "https://ekyc-web.vnpt.vn/altiss/cmt_notice2.svg",
        "notice3_icon": "https://ekyc-web.vnpt.vn/altiss/cmt_notice3.svg"
    },
    "MODAL_FACE_STYLE": {
        "face_icon": "https://ekyc-web.vnpt.vn/altiss/face_icon.svg",
        "close_icon": "https://ekyc-web.vnpt.vn/altiss/close_icon.svg",
        "notice1_icon": "https://ekyc-web.vnpt.vn/altiss/cmt_notice1.svg",
        "notice2_icon": "https://ekyc-web.vnpt.vn/altiss/cmt_notice2.svg",
        "notice3_icon": "https://ekyc-web.vnpt.vn/altiss/cmt_notice3.svg"
    },
    "OTHER_CONFIG": {
        "loading_icon": "https://ekyc-web.vnpt.vn/images/hdbank2/loading.gif",
        "loading_styles": "background-color: #000000; opacity: 0.7",
        "oval_web": "https://ekyc-web.vnpt.vn/animation/web_oval.json",
        "oval_mobile": "https://ekyc-web.vnpt.vn/kbsv/mobile_border.json",
        "notice_ani": "https://ekyc-web.vnpt.vn/animation/caution.json",
        "oval_title_color": "black",
        "description_oval_content": "Vui lòng tháo kính để xác thực chính xác hơn!",
        "description_oval": "text-align: center; color: white; font-weight: bold",
        "video_tutorial_oval": "https://ekyc-web.vnpt.vn/animation/video_tutorial_oval_dark.mp4"
    },
    "client_session": "WEB-SDK_Chrome-119_2.1.4.6_62febe91-a8e3-4f6d-a182-c2a7b19d39ff_1701707553379"
}